### ISSUE TITLE
server notification responseBodyV2

### ISSUE THREAD

**Issue by q657198385** [awa/go-iap#149]
Is there any plan to support server notification responseBodyV2?
https://developer.apple.com/documentation/appstoreservernotifications/responsebodyv2

**Comment by thilonel** [comment]
It'd be great to have that! I think whoever uses this library, will need to parse those server side notifications and it's a waste of time to write down the mapping again and again for all of us.

**Comment by thilonel** [comment]
@takecy is this repo still maintained? Is there a point in submitting PRs?

**Comment by takecy** [comment]
I'm sorry I missed it. We still maintaining. I'll check back soon.

**Comment by takecy** [comment]
Added struct definition for responseBodyV2.
Please check it out :)
https://github.com/awa/go-iap/releases/tag/v1.3.12

**Comment by thilonel** [comment]
Wow @takecy thank you, this was super fast! :)

I'm at the moment trying to figure out how to validate the JWT sent by Apple (the documentation is really poor, there are quite a few libs to use and I also don't know which cert or key I should use to provide against, but hopefully I can find some more time to figure these out) then maybe even that could be integrated into this lib.

I think it would save time to a lot of folks to just pass in the key and then get back the validated and decoded struct!

If you have any pointers for me on this, please do share! :)

Thanks again! 🙏 

PS: I think this issue is solved.

**Comment by takecy** [comment]
> the documentation is really poor 

I completely agree 😢 

> I think it would save time to a lot of folks to just pass in the key and then get back the validated and decoded struct!

I think so too. It was drafted as a separate issue.
https://github.com/awa/go-iap/issues/156

Thanks for your support!
