### ISSUE TITLE
question related to the naming of playstore VeirfyProduct and VerifySubscriptionV2 methods 

### ISSUE THREAD

**Issue by fans3210** [awa/go-iap#241]
as mentioned in the doc. VerifyProduct verifies the product status while VerifySubscriptionV2 verifies the subscription status. However, after checking the code and test case, found that there is no verifications of status such as purchase status or consumption status. Instead, it simply calls the purchases.product.get and purchases.subscriptionsv2.get. 

Expected methods to do the validation.

I might be wrong. Appreciated if you could clear some of my doubts. Thanks

**Comment by richzw** [comment]
Yes, the VerifyProduct and VerifySubscriptionV2 simply call the purchases.product.get and purchases.subscriptionsv2.get and return the details of the product and subscriptions to the caller, so the caller can do some specific verification such as validate the productionID or product type and so on since there are more fields of subscriptions that could be used in subscription validation. The VerifySubscriptionV2 simply call the purchases.subscriptionsv2.get without specific validation in here. 

If you have any more questions please let me know.

**Comment by fans3210** [comment]
I see. Just a bit confused by the naming of both methods. Thanks for the explanations.
